project:
  type: website
  output-dir: docs

website:
  title: "Epistemic Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: about.qmd
        text: About Author

format:
  html:
    theme: lux
    css: styles.css
    toc: true



