project:
  type: website
  output-dir: docs

website:
  title: "Epistemic Analysis"
  navbar:
    left:
      - href: introduction.qmd
        text: Introduction
      - href: blog.qmd
        text: Blog
    right: 
      - href: author.qmd
        text: About Author

format:
  html:
    theme: lux
    css: styles.css
    toc: true



